---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: samtools_cramsize
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::samtools=1.19.2
  - bioconda::htslib=1.19.1
